services:
  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
  logstash:
    image: logstash:8.11.3
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk
  kibana:
    image: kibana:8.11.3
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk
  ubuntu-logger:
    build: ./ubuntu-logger
    container_name: ubuntu-logger
    environment:
      - FILEBEAT_NAME=ubuntu-logger
    depends_on:
      - logstash
    networks:
      - elk
  almalinux-logger:
    build: ./almalinux-logger
    container_name: almalinux-logger
    environment:
      - FILEBEAT_NAME=almalinux-logger
    depends_on:
      - logstash
    networks:
      - elk
volumes:
  elasticsearch-data:
    driver: local
networks:
  elk:
    driver: bridge