name: ${FILEBEAT_NAME}

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/syslog
    - /var/log/messages

# Send logs to the Logstash container over the internal Docker network.
output.logstash:
  hosts: ["logstash:5044"]
