name: ${FILEBEAT_NAME}

filebeat.inputs:
- type: filestream
  id: python-app-stream
  enabled: true
  paths:
    - /var/log/app.log

processors:
  - add_host_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]